name: Github CI
on: [push]

jobs:
  linux32_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:x86-edge /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
        mv subconverter_linux64.tar.gz subconverter_linux32.tar.gz
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: subconverter_linux32.tar.gz
        path: $GITHUB_WORKSPACE

  linux64_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:amd64-edge /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: subconverter_linux64.tar.gz
        path: $GITHUB_WORKSPACE

  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        bash scripts/build.macos.release.sh
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: subconverter_darwin64.tar.gz
        path: $GITHUB_WORKSPACE

